dist: focal

addons:
  apt:
    sources:
      - sourceline: 'deb http://dl.yarnpkg.com/debian/ stable main'
        key_url: 'http://dl.yarnpkg.com/debian/pubkey.gpg'
      - sourceline: 'deb http://dl.google.com/linux/chrome/deb/ stable main'
        key_url: 'https://dl-ssl.google.com/linux/linux_signing_key.pub'
    packages:
      - chromium-chromedriver
      - google-chrome-stable
      - yarn
      - redis-server
services:
  - postgresql


_test_gem_pg: &_test_gem_pg
  stage: test

  language: ruby
  cache:
    bundler: true
    directories:
    - node_modules # NPM packages

  before_install:
    # - echo 'installing postgresql'
    # - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
    # - sudo cp /etc/postgresql/{9.6,12}/main/pg_hba.conf
    # - sudo service postgresql stop
    # - sudo service postgresql start 12
    # - postgres --version
    
  before_script:
    - echo before_script $COMPONENT
    - echo updating chrome driver
    - cd ruby/$COMPONENT
    - echo creating psql database
    - psql -c 'create database hyper_mesh_test_db;' -U postgres
    
